batch_size: 1
device: cuda
DR: dataset
save_root: predictions
model_path: saved_models/final_model.pth
num_workers: 4
val_vi_len: 630
frame_H: 32
frame_W: 64

# Module parameters setting
F_dim: 128
L_dim: 32
N_dim: 12
D_out_dim: 192
