batch_size: 1
lr: 0.001
device: cuda
test: false
DR: dataset
save_root: saved_models
num_workers: 4
num_epoch: 70
per_save: 3
partial: 1.0
train_vi_len: 16
val_vi_len: 630
frame_H: 32
frame_W: 64

# Module parameters setting
F_dim: 128
L_dim: 32
N_dim: 12
D_out_dim: 192

# Teacher Forcing strategy
tfr: 1.0
tfr_sde: 10
tfr_d_step: 0.1
tfr_min: 0.0
ckpt_path: null

# Training Strategy
fast_train: false
fast_partial: 0.4
fast_train_epoch: 5

# KL annealing strategy arguments
kl_anneal_type: Cyclical
kl_anneal_cycle: 10
kl_anneal_ratio: 1
