batch_size: 4
lr: 0.001
device: cuda
dataset_root: dataset
model_root: saved_models
seed: 35711
num_workers: 4
num_epoch: 110
per_save: 3
partial: 1.0
train_vi_len: 16
val_vi_len: 630
frame_H: 32
frame_W: 64

# Module parameters setting
F_dim: 128
L_dim: 32
N_dim: 12
D_out_dim: 192

# Teacher Forcing strategy
tfr_init: 1.0
tfr_sde: 2
tfr_d_step: 0.4
tfr_min: 0.0

# Training Strategy
fast_train: false
fast_partial: 0.4
fast_train_epoch: 10

# KL annealing strategy arguments
kl_anneal_type: Monotonic
kl_anneal_cycle: 10
kl_anneal_ratio: 1
