seed: 910615

# Data parameters
dataset_dir: "dataset"
train_json_path: "train.json"
objects_json_path: "objects.json"

# Model parameters
num_classes: 24
model_path: "model.pt"

# Training parameters
learning_rate: 0.001
batch_size: 32
epochs: 50
