seed: 910615

# Data parameters
dataset_dir: "dataset"
train_json_path: "train.json"
eval_json_path: "test.json"
objects_json_path: "objects.json"
result_dir: "results"

# Model parameters
num_classes: 24
model_path: "model.pth"

# Training parameters
checkpoint_dir: "checkpoints"
learning_rate: 0.0001
batch_size: 32
epochs: 150

image_size: 64
denoise_steps: 1000
